---
title: "Lab02_Mazo"
author: "Gustavo Mazo"
format: pdf
editor: visual
---

## Questão 1

Resposta:

 Estatísticas suficientes:

 n = quantidade de voos válidos;
 n_atrasados = quantidade de voos com ARRIVAL_DELAY > 10

 Percentual de atraso:

 Percentual = n_atrasados / n



## Questão 2

```{r}
library(readr)
library(dplyr)

getStats <- function(input, pos) {
  
  input |>
    filter(AIRLINE %in% c("AA", "DL", "UA", "US")) |>
    filter(
      !is.na(ARRIVAL_DELAY),
      !is.na(DAY),
      !is.na(MONTH),
      !is.na(AIRLINE)
    ) |>
    group_by(DAY, MONTH, AIRLINE) |>
    summarise(
      n = n(),
      n_atrasados = sum(ARRIVAL_DELAY > 10),
      .groups = "drop"
    )
}
```

## Questão 3

```{r}
banco <- read_csv_chunked(
  "flights.csv.zip",
  callback = DataFrameCallback$new(getStats),
  chunk_size = 100000,
  col_types = cols_only(
    AIRLINE = col_character(),
    DAY = col_integer(),
    MONTH = col_integer(),
    ARRIVAL_DELAY = col_double()
  )
)
```

## Questão 4:

```{r}
computeStats <- function(stats_parciais) {
  
  stats_parciais |>
    group_by(DAY, MONTH, AIRLINE) |>
    summarise(
      n = sum(n),
      n_atrasados = sum(n_atrasados),
      .groups = "drop"
    ) |>
    mutate(
      Data = as.Date(
        paste(2015, MONTH, DAY, sep = "-")
      ),
      Perc = n_atrasados / n,
      Cia = AIRLINE
    ) |>
    select(Cia, Data, Perc)
}

stats <- computeStats(banco)
```

## Questão 5:

```{r}
library(devtools)
library(ggcal)
library(ggplot2)
```

```{r}
pal <- scale_fill_gradient(
  low = "#4575b4",
  high = "#d73027"
)

baseCalendario <- function(stats, cia) {
  
  dados_cia <- stats |>
    filter(Cia == cia)
  
  ggcal(dados_cia$Data,dados_cia$Perc)
}

cAA <- baseCalendario(stats, "AA")
cDL <- baseCalendario(stats, "DL")
cUA <- baseCalendario(stats, "UA")
cUS <- baseCalendario(stats, "US")

cAA + pal + ggtitle("Atrasos - AA")
cDL + pal + ggtitle("Atrasos - DL")
cUA + pal + ggtitle("Atrasos - UA")
cUS + pal + ggtitle("Atrasos - US")
```

```{r}
Sys.setenv(TZ = "America/Sao_Paulo")
Sys.time()
```

