---
title: "Lista05_Mazo"
author: "Gustavo Mazo Vieira"
format: pdf
editor: visual
---

## Conexão R \>\>\> SQL

```{r}
library(DBI)
library(RSQLite)

con <- dbConnect(SQLite(), "me315.sqlite")
```

## Questão 1

```{sql connection = con}
SELECT PNAME, ACRES, ACRES * 1.2 FROM PRESERVE
```

## Questão 2

```{sql connection = con}
SELECT PNAME, ACRES, ACRES * 1.0/3.0 FROM PRESERVE
```

# Questão 3

```{sql connection = con}
SELECT PNAME, FEE, (FEE + 50) / 2.0 FROM PRESERVE
```

## Questão 4

```{sql connection = con}
SELECT AVG(ACRES), MAX(ACRES), MIN(ACRES) FROM PRESERVE
WHERE STATE = "AZ"
```

## Questão 5

```{sql connection = con}
SELECT MIN(PNAME) FROM PRESERVE
```

## Questão 6

```{sql connection = con}
SELECT COUNT(FEE) FROM PRESERVE
WHERE FEE <> 0
```

## Questão 7

```{sql connection = con}
SELECT COUNT(PNAME) - COUNT(DISTINCT PNAME) FROM PRESERVE
```

## Questão 8

```{sql connection = con}
SELECT AVG(0.02 * ACRES) FROM PRESERVE
WHERE STATE = 'AZ'
```

## Questão 9

```{sql connection = con}
SELECT ENO, ENAME, SALARY AS OLDSALARY, SALARY * 1.1 AS NEWSALARY FROM EMPLOYEE
ORDER BY NEWSALARY
```

## Questão 10

```{sql connection = con}
SELECT ENO, ENAME, SALARY AS OLDSALARY, SALARY * 1.1 AS NEWSALARY FROM EMPLOYEE
WHERE NEWSALARY > 2000
ORDER BY NEWSALARY 
```

## Questão 11

```{sql connection = con}
SELECT SUM(SALARY), AVG(SALARY), MAX(SALARY), MIN(SALARY) FROM EMPLOYEE
```

## Questão 12

```{sql connection = con}
SELECT COUNT(DNO) FROM EMPLOYEE
WHERE DNO = 20
```

## Questão 13

```{sql connection = con}
SELECT COUNT(DISTINCT DNO) FROM EMPLOYEE
```

```{r}
Sys.setenv(TZ = "America/Sao_Paulo")
Sys.time()
```
